name: cicd pipeline

on: [push]
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: docker build
        run: docker build -t ruslanjo/cw_5:$GITHUB_REF_NAME-$GITHUB_RUN_ID
      - name: docker login
        run: echo {{ secrets.DOCKER_HUB_TOKEN }} | docker login -u ruslanjo --password-stdin
      - name: docker push
        run: docker push ruslanjo/cw_5:$GITHUB_REF_NAME-$GITHUB_RUN_ID
